

using System;
using System.Windows.Forms;

namespace SpreadsheetApp
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable. This container holds references to all disposable components.
        /// Automatically disposed in Dispose() if not null.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes managed resources used by the form (e.g., controls, buttons, event handlers).
        /// This override ensures proper cleanup and avoids memory leaks.
        /// </summary>
        /// <param name="disposing">Whether to dispose managed resources explicitly</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                // Dispose each managed component (e.g., buttons, DataGridView)
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Initializes and lays out all UI controls on the form.
        /// This method is auto-generated by the Windows Forms Designer.
        /// It creates the DataGridView for spreadsheet display, 
        /// and two buttons (Load and Save) for interacting with CSV files.
        /// </summary>
        private void InitializeComponent()
        {
            dataGridView1 = new DataGridView();
            btnLoad = new Button();
            btnSave = new Button();
            ((System.ComponentModel.ISupportInitialize)dataGridView1).BeginInit();
            SuspendLayout();
            // 
            // dataGridView1
            // 
            dataGridView1.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridView1.Location = new Point(12, 23);
            dataGridView1.Name = "dataGridView1";
            dataGridView1.RowHeadersWidth = 51;
            dataGridView1.Size = new Size(776, 327);
            dataGridView1.TabIndex = 0;
            dataGridView1.CellContentClick += dataGridView1_CellContentClick;
            dataGridView1.CellEndEdit += dataGridView1_CellEndEdit;
            // 
            // btnLoad
            // 
            btnLoad.Location = new Point(509, 371);
            btnLoad.Name = "btnLoad";
            btnLoad.Size = new Size(189, 54);
            btnLoad.TabIndex = 1;
            btnLoad.Text = "Load";
            btnLoad.UseVisualStyleBackColor = true;
            btnLoad.Click += btnLoad_Click;
            // 
            // btnSave
            // 
            btnSave.Location = new Point(108, 371);
            btnSave.Name = "btnSave";
            btnSave.Size = new Size(189, 54);
            btnSave.TabIndex = 2;
            btnSave.Text = "Save";
            btnSave.UseVisualStyleBackColor = true;
            btnSave.Click += btnSave_Click;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(800, 450);
            Controls.Add(btnSave);
            Controls.Add(btnLoad);
            Controls.Add(dataGridView1);
            Name = "Form1";
            Text = "SpreadsheetApp";
            Load += Form1_Load;
            ((System.ComponentModel.ISupportInitialize)dataGridView1).EndInit();
            ResumeLayout(false);
        }

        #endregion
        // === Private UI components declared here for WinForms Designer ===

        /// <summary>
        /// Main spreadsheet grid, used to display and edit cell content.
        /// </summary>
        private System.Windows.Forms.DataGridView dataGridView1;

        /// <summary>
        /// Button to load spreadsheet content from a CSV file.
        /// </summary>
        private System.Windows.Forms.Button btnLoad;

        /// <summary>
        /// Button to save spreadsheet content to a CSV file.
        /// </summary>
        private System.Windows.Forms.Button btnSave;
    }
}
